quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
  swagger-ui:
    always-include: true
smallrye:
  jwt:
    sign:
      key:
        location: rsaPrivatekey.pem
mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
"%test":
  quarkus:
    datasource:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5433/lingkar_test
      username: subrutin
      password: subrutin   
      devservices:
        enabled: true
        port: 5433
        db-name: lingkar_test
        username: subrutin
        password: subrutin
        image-name: postgres:15.3
    hibernate-orm:
      database:
        generation: drop-and-create
      sql-load-script: import-local.sql
"%local":
  quarkus:
    datasource:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5433/lingkar_dev
      username: subrutin
      password: subrutin   
      devservices:
        enabled: true
        port: 5433
        db-name: lingkar_dev
        username: subrutin
        password: subrutin
        image-name: postgres:15.3
    hibernate-orm:
      database:
        generation: drop-and-create
      sql-load-script: import-local.sql  